---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy
    # - swarm_init

- name: Managers servers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join
