---
- name: user
  hosts: demo
  tasks:
    - name: Create user
      vars:
        user: khan109
      user:
        name: "{{ user }}"
        state: present
      become: true
      debugger: always