---
- name: user
  hosts: demo
  vars_prompt:
    - name: user
      prompt: "How user?"
      private: no 
  tasks:
    - name: Create user
      user:
        name: "{{ user }}"
        state: absent
      become: true