---
- name: Установка Docker
  block:
    - name: Добавляем universe
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update-cache: true
        cache_valid_time: 86400
    - name: Добавление ключа Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Установка стабильного репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Установка Docker
      ansible.builtin.apt:
        name: docker-ce
        update-cache: true

    - name: Проверка что Docker установлен и перезагружен
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
  become: true
- name: Установка Docker-compose
  ansible.builtin.apt:
    name: docker-compose-plugin
    update-cache: true
  become: true

- name: Завершение установки
  block:
    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups: docker

    - name: Перезагрузка
      ansible.builtin.reboot:
  become: true
